### ISSUE TITLE
Wrong Cloudflare Zone returned

### ISSUE THREAD

**Issue by timothystewart6** [michaelkourlas/node-cloudflare-dynamic-dns#5]
When updating a record, the wrong zone is getting returned, thus updating/creating the correct record in the wrong zone. It always returns the first element in the array, rather than the first element of the filtered results in the array.  

The same goes for records.  It would not update an existing record.

**Comment by Trinitas** [comment]
Could you make it so it could update multiple records (c name etc) on same address? Or make a new pull?

**Comment by timothystewart6** [comment]
Hi.  Not sure I follow.  Are you requesting a feature or asking that I update my PR to handle this use case?  The example only shows one record at a time.  All you would have to do is loop over all your records.  If this is a feature request, open a new issue.

**Comment by Trinitas** [comment]
Well i don't need it anymore since I deleted my other Cname, But there may be others who wants this feature. I may send an feature request in the future if I need to make more record names.  Thanks anyway

**Comment by timothystewart6** [comment]
Sure, it's a valid request but open a separate issue for it.

**Comment by michaelkourlas** [comment]
This will be fixed in 1.0.1.
